"""Discrete-event stochastic quantum-network simulator (Wave 3, item 1).

The optimizer-facing model of this project is *parametric*: every bundle
carries an expected utility ``u = w * P_succ * (1 + margin) - ...``, where
``P_succ`` is a product of generation / purification / swap probabilities.
Such expected-value models hide three kinds of stochastic reality:

1. **Event-level failures** -- a generation attempt is a Bernoulli trial, a
   purification round is a Bernoulli trial, a swap is a Bernoulli trial.  The
   *realized* number of served requests in one execution is a random variable
   with a spread around the expectation, not the expectation itself.
2. **Memory contention** -- pairs are held in finite-capacity node memories
   while other requests generate; a pair that the parametric model assumed
   would fit can be blocked when events actually interleave in time.
3. **Decoherence drift** -- generation retries and waiting stretch the storage
   time, so the *delivered* fidelity is a random variable whose tail can fall
   below the fidelity SLA even when the mean is fine.

This module provides ``StochasticEventSimulator``, a discrete-event engine that
samples the full pipeline

    generation -> storage -> purification -> swapping -> delivery

for every request of a *plan* (a solver selection ``[(rid, bid), ...]``) and
over ``N`` Monte-Carlo realizations, and reports

* the sampled expected utility ``E[U]`` and variance ``Var[U]``,
* the served-request distribution and per-request sampled success
  probability versus the parametric ``success_probability``,
* the delivered-fidelity distribution (5th / 50th / 95th percentiles),
* the SLA-violation probability ``P(F < F_min)`` over delivered pairs,
* a failure-cause breakdown (purification / swap / memory-blocked / timeout).

The engine is deterministic under a seed: realization ``i`` derives sub-seed
``seed * 100000 + i``.

Model notes (chosen to mirror the parametric bundle math exactly so that the
reliability *gap* between the two is a real finding, not an artifact):

* A link provisioned with ``q`` purification rounds needs ``2**q`` raw Bell
  pairs.  Each raw pair is generated by Bernoulli trials with the link's
  ``generation_probability`` (retried by default).  Purification then runs
  ``q`` rounds; round ``r`` performs ``2**(q-r-1)`` BBPSSW operations, each
  succeeding with probability ``s(f_r)``, and the request fails if any
  operation in any round fails.  This reproduces the parametric
  ``P = g**(2**q) * prod_r s(f_r)**(2**(q-r-1))``.
* After purification each link holds one pair in the endpoint memories; the
  path is then swapped end-to-end with ``L - 1`` sequential swaps, each
  succeeding with probability ``swap_success``.
* Stored pairs decay under the T1/T2 model shared with the schedulers; the
  fidelity used at every purification/swap/delivery step is the *decayed*
  fidelity, so delivered fidelity is a random variable driven by real waiting
  times.
* A request whose memory allocation would exceed a node's capacity fails
  with cause ``memory_blocked``; requests interleave through a shared event
  heap so memory contention is real.
"""

import heapq
import math
import random
from typing import Dict, List, Optional, Tuple

from fidelity.fidelity_model import FidelityModel
from routing.success_probability import SuccessProbabilityModel


def storage_decay(hold_time: float, tau_mem: float,
                  t1: Optional[float] = None) -> float:
    """T1/T2 storage-decay multiplier (identical model to the schedulers).

    ``F(t) = F0 * 0.25 * (1 + 3 e^{-t/T2} (1 + e^{-t/T1})/2)`` with
    ``T2 = tau_mem`` and ``T1 = 2 * T2`` by default.  Asymptotes to the
    fully-mixed floor ``1/4`` rather than to zero.
    """
    if hold_time <= 0 or tau_mem <= 0:
        return 1.0
    t2 = tau_mem
    t1v = t1 if t1 and t1 > 0 else 2.0 * t2
    return 0.25 * (1.0 + 3.0 * math.exp(-hold_time / t2)
                   * (1.0 + math.exp(-hold_time / t1v)) / 2.0)


def delivered_utility_if_success(bundle: dict) -> float:
    """Utility contributed when a request is *actually* delivered.

    ``bundle["utility"]`` already folds in ``success_probability``; in the
    simulator delivery is sampled, so the realized contribution of a delivered
    request is the utility *conditional on success*, i.e. the parametric
    expectation divided by its own success probability.
    """
    p = float(bundle.get("success_probability", 1.0))
    if p <= 1e-12:
        return float(bundle.get("utility", 0.0))
    return float(bundle.get("utility", 0.0)) / p


class StochasticEventSimulator:
    """Discrete-event engine that samples the entanglement pipeline.

    ``topology`` is an instances-style dict with ``nodes``, ``edges``,
    ``link_params`` and ``memory_capacities``.  A *plan* is a list of
    ``(request_id, bundle_id)`` pairs drawn from a solver selection together
    with the full bundle dicts.
    """

    def __init__(self, topology: dict,
                 tau_mem: float = 5.0, t1: Optional[float] = None,
                 swap_success: float = 1.0,
                 purification_time: float = 1.0,
                 swap_time: float = 1.0,
                 max_generation_attempts: int = 200,
                 allow_generation_retries: bool = True,
                 fidelity_noise_sigma: Optional[float] = None,
                 seed: int = 42):
        self.topology = topology
        self.tau_mem = tau_mem
        self.t1 = t1
        self.swap_success = swap_success
        self.purification_time = purification_time
        self.swap_time = swap_time
        self.max_generation_attempts = max_generation_attempts
        self.allow_generation_retries = allow_generation_retries
        self.fidelity_noise_sigma = fidelity_noise_sigma
        self.seed = seed
        self._link_params = topology["link_params"]

    # ------------------------------------------------------------------
    # public API
    # ------------------------------------------------------------------
    def simulate_plan(self, bundles: List[dict],
                      selected: List[Tuple[str, str]],
                      n_realizations: int = 100,
                      sla_thresholds: Optional[Dict[str, float]] = None,
                      track_events: bool = False) -> Dict:
        """Evaluate ``selected`` over ``n_realizations`` stochastic runs.

        Returns an aggregate reliability report (see ``_aggregate`` for the
        exact schema, including ``E[U]``, ``Var[U]``, fidelity quantiles,
        ``sla_violation_prob``, ``n_sla_ok`` and the per-request breakdown).
        """
        bundle_map = {(b["request_id"], b["bundle_id"]): b for b in bundles}
        plan = [(rid, bid, bundle_map[(rid, bid)]) for rid, bid in selected
                if (rid, bid) in bundle_map]
        # a plan must contain at most one bundle per request (a solver
        # selection already satisfies this); if a caller passes several
        # bundles for the same request, keep the highest-utility one.
        best_by_rid: Dict[str, Tuple[str, dict]] = {}
        for rid, bid, bundle in plan:
            if rid not in best_by_rid or bundle["utility"] > best_by_rid[rid][1]["utility"]:
                best_by_rid[rid] = (bid, bundle)
        plan = [(rid, bid, bundle) for rid, (bid, bundle) in best_by_rid.items()]
        sla = dict(sla_thresholds or {})
        if not plan:
            return self._aggregate(plan, [], n_realizations, sla)

        realizations = []
        for i in range(n_realizations):
            rng = random.Random(self.seed * 100000 + i)
            events = [] if track_events else None
            res = self._run_realization(plan, rng, events, sla)
            res["realization"] = i
            realizations.append(res)

        return self._aggregate(plan, realizations, n_realizations, sla)

    def per_request_reliability(self, bundles: List[dict],
                                selected: List[Tuple[str, str]],
                                n_realizations: int = 100,
                                sla_thresholds: Optional[Dict[str, float]] = None,
                                ) -> Dict:
        """Per-request parametric vs sampled success and SLA statistics."""
        return self.simulate_plan(bundles, selected,
                                  n_realizations=n_realizations,
                                  sla_thresholds=sla_thresholds)["per_request"]

    # ------------------------------------------------------------------
    # single realization
    # ------------------------------------------------------------------
    def _run_realization(self, plan, rng, events, sla) -> Dict:
        mem_cap = self.topology["memory_capacities"]
        occupancy = {n: 0 for n in mem_cap}
        delivered = []     # (rid, fidelity, latency, cost, weight, fmin)
        failures = []      # (rid, cause)
        outcomes = {}      # rid -> "served" | "failed:cause"
        counter = [0]

        def _seq():
            counter[0] += 1
            return counter[0]

        pending = []       # (end_time, order, rid, cursor)
        states = {}        # rid -> state dict

        for idx, (rid, bid, bundle) in enumerate(plan):
            st = {
                "bundle": bundle,
                "rid": rid,
                "slots": {},            # node -> held slots (per-request)
                "raw": {},              # link_idx -> list of pair dicts
                "current": None,        # current merged pair during swaps
                "current_has": False,
                "link_pairs": [],       # list of link pair dicts
                "attempts": 0,
                "done": False,
            }
            states[rid] = st
            tasks = self._build_task_chain(bundle, st, events)
            st["tasks"] = tasks
            st["_order"] = idx
            heapq.heappush(pending, (0.0, _seq(), rid, 0))

        while pending:
            end_time, order, rid, cursor = heapq.heappop(pending)
            st = states[rid]
            if st["done"]:
                continue
            t = end_time
            tasks = st["tasks"]

            while not st["done"]:
                if cursor >= len(tasks):
                    self._deliver(rid, st, t, delivered, outcomes, occupancy, rng)
                    break
                kind, payload = tasks[cursor]
                if kind == "gen":
                    li, _pi, dur, g, u, v, _f0 = payload
                    if (occupancy[u] >= mem_cap[u]
                            or occupancy[v] >= mem_cap[v]):
                        self._fail(rid, st, "memory_blocked", failures,
                                   outcomes, occupancy)
                        break
                    if rng.random() < g:
                        self._occupy(st, u)
                        self._occupy(st, v)
                        st["raw"][li].append({"f": payload[6], "t0": t,
                                              "ep": (u, v)})
                        if events is not None:
                            events.append(("generated", rid, li, t))
                        cursor += 1
                        continue
                    # generation failure: retry unless exhausted
                    if not self.allow_generation_retries:
                        self._fail(rid, st, "generation_failed", failures,
                                   outcomes, occupancy)
                        break
                    st["attempts"] += 1
                    if st["attempts"] >= self.max_generation_attempts:
                        self._fail(rid, st, "generation_timeout", failures,
                                   outcomes, occupancy)
                        break
                    heapq.heappush(pending, (t + dur, _seq(), rid, cursor))
                    break

                elif kind == "purify_round":
                    li, rnd = payload
                    lst = st["raw"][li]
                    n_ops = len(lst) // 2
                    f_r = sum(self._decayed(p, t) for p in lst) / len(lst)
                    p_succ = SuccessProbabilityModel.purification_bbpssw_success(
                        max(min(f_r, 1.0), 0.0))
                    ok = all(rng.random() < p_succ for _ in range(n_ops))
                    if not ok:
                        self._fail(rid, st, "purification_failed", failures,
                                   outcomes, occupancy)
                        break
                    nf = SuccessProbabilityModel._purified_fidelity(f_r)
                    for _ in range(n_ops):
                        self._release(st, st["raw"][li][0]["ep"][0])
                        self._release(st, st["raw"][li][0]["ep"][1])
                    u, v = st["raw"][li][0]["ep"]
                    st["raw"][li] = [{"f": nf, "t0": t, "ep": (u, v)}
                                     for _ in range(n_ops)]
                    if events is not None:
                        events.append(("purified", rid, li, t))
                    cursor += 1
                    continue

                elif kind == "provision_end":
                    st["link_pairs"] = [st["raw"][li][0]
                                        for li in range(st["n_links"])]
                    cursor += 1
                    continue

                elif kind == "swap":
                    k = payload[0]
                    a = st["link_pairs"][0]
                    b = st["link_pairs"][1]
                    if rng.random() >= self.swap_success:
                        self._fail(rid, st, "swap_failed", failures,
                                   outcomes, occupancy)
                        break
                    f_a = self._decayed(a, t)
                    f_b = self._decayed(b, t)
                    merged = FidelityModel.entanglement_swapping(f_a, f_b)
                    mid = b["ep"][0]
                    self._release(st, mid)
                    self._release(st, mid)
                    st["link_pairs"] = st["link_pairs"][1:]
                    st["link_pairs"][0] = {"f": merged, "t0": t,
                                           "ep": (a["ep"][0], b["ep"][1])}
                    if events is not None:
                        events.append(("swapped", rid, mid, t))
                    cursor += 1
                    continue

                else:
                    raise ValueError(f"unknown task kind {kind!r}")

        return {
            "delivered": delivered,
            "failures": failures,
            "n_delivered": len(delivered),
            "n_sla_ok": sum(1 for (_r, f, _l, _c, _w, fm) in delivered
                            if f >= (sla.get(_r, fm if fm is not None else 0.0))),
            "total_utility": sum(delivered_utility_if_success(states[rid]["bundle"])
                                 for rid, _f, _l, _c, _w, _fm in delivered),
            "outcomes": outcomes,
            "events": events,
        }

    # ------------------------------------------------------------------
    # memory + fidelity helpers
    # ------------------------------------------------------------------
    def _occupy(self, st, node):
        st["slots"][node] = st["slots"].get(node, 0) + 1

    def _release(self, st, node):
        st["slots"][node] = max(0, st["slots"].get(node, 0) - 1)

    def _decayed(self, pair, t) -> float:
        return pair["f"] * storage_decay(t - pair["t0"], self.tau_mem, self.t1)

    def _release_all(self, st, occupancy):
        for node, n in st["slots"].items():
            if n > 0:
                occupancy[node] = max(0, occupancy[node] - n)
                st["slots"][node] = 0

    def _fail(self, rid, st, cause, failures, outcomes, occupancy):
        self._release_all(st, occupancy)
        st["done"] = True
        failures.append((rid, cause))
        outcomes[rid] = f"failed:{cause}"

    def _deliver(self, rid, st, t, delivered, outcomes, occupancy, rng=None):
        pair = st["link_pairs"][0]
        fid = self._decayed(pair, t)
        if self.fidelity_noise_sigma:
            from optimization.chance_constrained import sample_truncnorm
            if rng is None:
                rng = random.Random(self.seed * 100000 + 999999)
            fid = sample_truncnorm(fid, self.fidelity_noise_sigma, rng,
                                   lo=0.0, hi=1.0)
        b = st["bundle"]
        self._release_all(st, occupancy)
        st["done"] = True
        outcomes[rid] = "served"
        delivered.append((rid, fid, t,
                          float(b.get("bell_pair_cost", 0.0)),
                          float(b.get("weight", 1.0)),
                          b.get("min_fidelity")))

    # ------------------------------------------------------------------
    # task-chain construction
    # ------------------------------------------------------------------
    def _purification_rounds(self, bundle: dict) -> int:
        """Recover the per-link purification round count of a bundle.

        Bundle dicts carry it either explicitly (``purification_rounds``) or
        encoded in the legacy ``bundle_id`` (``..._q{k}``).
        """
        v = bundle.get("purification_rounds")
        if v is not None:
            return int(v)
        bid = bundle.get("bundle_id", "")
        import re
        m = re.search(r"_q(\d+)$", bid)
        if m:
            return int(m.group(1))
        return 0

    def _build_task_chain(self, bundle: dict, st, events) -> List[Tuple[str, tuple]]:
        """Translate a bundle into a strictly-sequential event chain per request.

        Mirrors the parametric model exactly (see module docstring): each link
        generates ``2**q`` raw pairs, runs ``q`` purification rounds with
        ``2**(q-r-1)`` operations each, then the path is swapped linearly.
        """
        path = bundle["path"]
        q = self._purification_rounds(bundle)
        n_links = len(path) - 1
        tasks = []
        for li in range(n_links):
            u, v = path[li], path[li + 1]
            lp = self._link_params.get((u, v), self._link_params.get((v, u)))
            if lp is None:
                raise ValueError(f"link {u}-{v} not in topology link_params")
            g = lp["generation_probability"]
            dur = lp["latency"]
            f0 = lp["raw_fidelity"]
            st["raw"][li] = []
            n_raw = 2 ** q
            for pi in range(n_raw):
                tasks.append(("gen", (li, pi, dur, g, u, v, f0)))
            for rnd in range(q):
                tasks.append(("purify_round", (li, rnd)))
            # one purified pair per link survives to the swap stage
        tasks.append(("provision_end", (n_links,)))
        for k in range(n_links - 1):
            tasks.append(("swap", (k, path[k + 1])))
        st["n_links"] = n_links
        return tasks

    # ------------------------------------------------------------------
    # aggregation
    # ------------------------------------------------------------------
    def _aggregate(self, plan, realizations, n_realizations,
                   sla_thresholds: Dict[str, float]) -> Dict:
        import statistics

        if not realizations:
            param_exp = sum(b["utility"] for _, _, b in plan)
            return {"n_realizations": 0, "n_requests": len(plan),
                    "param_expected_utility": param_exp,
                    "e_utility": 0.0, "var_utility": 0.0, "std_utility": 0.0,
                    "utility_gap": param_exp,
                    "e_served": 0.0, "served_ratio": 0.0,
                    "e_delivered_fidelity": float("nan"),
                    "fid_q05": float("nan"), "fid_q50": float("nan"),
                    "fid_q95": float("nan"),
                    "sla_violation_prob": 0.0, "e_latency": float("nan"),
                    "n_delivered_total": 0, "failure_causes": {},
                    "per_request": {}}

        util_samples = [r["total_utility"] for r in realizations]
        served_samples = [r["n_delivered"] for r in realizations]
        e_util = sum(util_samples) / len(util_samples)
        var_util = statistics.pvariance(util_samples) if len(util_samples) > 1 else 0.0

        fid_all, lat_all, sla_below = [], [], 0
        n_deliv = 0
        for r in realizations:
            for (_rid, fid, lat, _c, _w, fmin) in r["delivered"]:
                fid_all.append(fid)
                lat_all.append(lat)
                n_deliv += 1
                fmin_v = sla_thresholds.get(_rid, fmin if fmin is not None else 0.0)
                if fid < fmin_v:
                    sla_below += 1

        fid_sorted = sorted(fid_all)

        def _q(p):
            if not fid_sorted:
                return float("nan")
            return fid_sorted[int(p * (len(fid_sorted) - 1))]

        per_request = {}
        for rid, bid, bundle in plan:
            deliv = [r["outcomes"].get(rid, "failed") == "served"
                     for r in realizations]
            p_sampled = sum(deliv) / max(n_realizations, 1)
            fids_here = []
            for r in realizations:
                for (_rid, fid, _l, _c, _w, _fm) in r["delivered"]:
                    if _rid == rid:
                        fids_here.append(fid)
            fmin_v = sla_thresholds.get(rid, bundle.get("min_fidelity", 0.0))
            sla_viol = (sum(1 for f in fids_here if f < fmin_v)
                        / max(len(fids_here), 1)) if fids_here else float("nan")
            per_request[rid] = {
                "p_model": bundle.get("success_probability", 0.0),
                "p_sampled": p_sampled,
                "n_delivered": sum(deliv),
                "mean_delivered_fidelity": (sum(fids_here) / len(fids_here)
                                            if fids_here else float("nan")),
                "sla_violation_prob": sla_viol,
            }

        cause_counts = {}
        for r in realizations:
            for (_rid, cause) in r["failures"]:
                cause_counts[cause] = cause_counts.get(cause, 0) + 1
        total_failures = sum(cause_counts.values())
        cause_frac = {k: v / max(total_failures, 1)
                      for k, v in sorted(cause_counts.items())}

        n_sla_ok = sum(r["n_sla_ok"] for r in realizations)
        param_exp = sum(b["utility"] for _, _, b in plan)

        return {
            "n_realizations": n_realizations,
            "n_requests": len(plan),
            "param_expected_utility": param_exp,
            "e_utility": e_util,
            "var_utility": var_util,
            "std_utility": math.sqrt(var_util),
            "utility_gap": param_exp - e_util,
            "e_served": sum(served_samples) / len(served_samples),
            "served_ratio": sum(served_samples) / max(len(plan) * n_realizations, 1),
            "e_delivered_fidelity": (sum(fid_all) / len(fid_all)
                                     if fid_all else float("nan")),
            "fid_q05": _q(0.05),
            "fid_q50": _q(0.5),
            "fid_q95": _q(0.95),
            "sla_violation_prob": (sla_below / max(n_deliv, 1)) if n_deliv else 0.0,
            "e_latency": (sum(lat_all) / len(lat_all) if lat_all else float("nan")),
            "n_delivered_total": n_deliv,
            "n_sla_ok": n_sla_ok,
            "failure_causes": cause_frac,
            "per_request": per_request,
        }
